SC_CONFIG_MAIN As screen:
    Fill: =RGBA(219, 219, 219, 1)

    CompMenuVar_4 As CompMenuVar:
        Default: ="Config."
        Height: =Parent.Height
        Width: =125

    Label1_1 As label:
        BorderColor: =RGBA(0, 89, 178, 1)
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =48
        Size: =20
        Text: ="SC_CONFIG_MAIN" 
        Width: =461
        X: =471
        Y: =75
        ZIndex: =2

    Label2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(149, 149, 149, 1)
        BorderThickness: =2
        Color: =RGBA(250, 250, 250, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(0, 36, 71, 1)
        OnSelect: =Set(showColorPicker, true)
        Size: =13
        Text: ="Change Color Scheme"
        Width: =266
        X: =454
        Y: =330
        ZIndex: =3

    CompColorPicker_1 As CompColorPicker:
        Height: =CompColorPicker_1.ReservedHeight
        Visible: =showColorPicker
        Width: =CompColorPicker_1.ReservedWidth
        X: =207
        ZIndex: =4

