SC_CONFIG_MAIN As screen:
    Fill: =RGBA(219, 219, 219, 1)
    OnVisible: |-
        = Set(closeRequest, false );
        Set(blnShowMsgBarArea, true);
        UpdateContext({messageToShow:"This is a notification message.....
        Component에 공용사용가능하 Message bar를 추가했습니다.. 사용방법은 버튼위 코드를 참고하세요.
        필요한 부분은 추가하시거나 수정하세요."});
        UpdateContext({typeToShow:"Notification"}); //Types : Notification|Error|Announcement|Confirmation
        UpdateContext({blnShow: false });
        UpdateContext({blnShow: true });

    Rectangle1 As rectangle:
        BorderColor: =RGBA(0, 89, 178, 1)
        BorderThickness: =1
        Fill: =RGBA(0, 0, 0, 0)
        Height: =177
        Width: =1101
        X: =768
        Y: =852
        ZIndex: =1

    CompGNB_4 As CompGNBMenubar:
        Default: ="Config."
        Height: =Parent.Height
        items: =colLNBMenu
        Width: =181.26
        X: =0.00
        ZIndex: =2

    btnChangeColor As label:
        Align: =Align.Center
        BorderColor: =RGBA(149, 149, 149, 1)
        BorderThickness: =2
        Color: =RGBA(250, 250, 250, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(0, 36, 71, 1)
        Height: =71
        OnSelect: =Set(showColorPicker, true)
        PaddingRight: =7.25
        PaddingTop: =7.25
        Size: =18.85
        Text: ="Change Color Scheme"
        Width: =385.73
        X: =768
        Y: =670
        ZIndex: =3

    CompColorPicker_1 As CompColorPicker:
        Height: =CompColorPicker_1.ReservedHeight
        Visible: =showColorPicker
        Width: =1221.00
        X: =300.17
        ZIndex: =4

    Comp2ndMenu_4 As Comp2ndMenubar:
        Width: =1799.60
        X: =120.40000000000009
        Y: =35
        ZIndex: =5

    lblCurrentScrName_4 As label:
        BorderColor: =RGBA(0, 89, 178, 1)
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =48
        PaddingRight: =7.25
        PaddingTop: =7.25
        Size: =21.76
        Text: =App.ActiveScreen.Name
        Width: =292.92
        X: =204
        Y: =956
        ZIndex: =6

    bltnShowNtfctn As button:
        BorderColor: |+
            =ColorFade(Self.Fill, -45%)
            
        Color: =RGBA(0, 0, 0, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(241, 241, 241, 1)
        Height: =61
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(0, 51, 102, 1), -20%)
        OnSelect: |-
            =
            //메시지바 이용위해서는 아래 코드 이용 
            //메시지 바 슬라이딩 지속시간은 timerShowAlert:OnTimerStart에서 정의 (현재 1900)
            
            Set(closeRequest, false );
            Set(blnShowMsgBarArea, true);
            UpdateContext({messageToShow:"This is a notification message.....
            Component에 공용사용가능하 Message bar를 추가했습니다.. 사용방법은 버튼속 코드를 참고하세요.
            필요한 부분은 추가하시거나 수정하세요."});
            UpdateContext({typeToShow:"Notification"}); //Types : Notification|Error|Announcement|Confirmation
            UpdateContext({blnShow: false });
            UpdateContext({blnShow: true });
        RadiusBottomLeft: =2
        RadiusBottomRight: =2
        RadiusTopLeft: =2
        RadiusTopRight: =2
        Size: =20
        Text: ="Notification"
        Width: =218
        X: =810
        Y: =943
        ZIndex: =7

    bltnShowAncmnt As button:
        BorderColor: |+
            =ColorFade(Self.Fill, -45%)
            
        Color: =RGBA(0, 0, 0, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(241, 241, 241, 1)
        Height: =61
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(0, 51, 102, 1), -20%)
        OnSelect: |
            =Set(closeRequest, false );
            Set(blnShowMsgBarArea, true);
            UpdateContext({messageToShow:"This is an announement message....
            최근 임직원의 ID와 패스워드와 같은 계정정보를 탈취하려는 피싱메일 공격이 급증하고 있으며,
            탈취한 임직원 계정을 통해 그룹 임직원을 대상으로 광범위하게 피싱메일이 발송되고 있어, 긴급하게 전임직원을 대상으로 안내를 드립니다."});
            UpdateContext({typeToShow:"Announcement"});
            UpdateContext({blnShow: false });
            UpdateContext({blnShow: true });
        RadiusBottomLeft: =2
        RadiusBottomRight: =2
        RadiusTopLeft: =2
        RadiusTopRight: =2
        Size: =20
        Text: ="Announcement"
        Width: =218
        X: =1095
        Y: =943
        ZIndex: =8

    bltnShowError As button:
        BorderColor: |+
            =ColorFade(Self.Fill, -45%)
            
        Color: =RGBA(0, 0, 0, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(241, 241, 241, 1)
        Height: =61
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(0, 51, 102, 1), -20%)
        OnSelect: |
            =Set(closeRequest, false );
            Set(blnShowMsgBarArea, true);
            UpdateContext({messageToShow:"This is an error message polulated by the component"});
            UpdateContext({typeToShow:"Error"});
            UpdateContext({blnShow: false });
            UpdateContext({blnShow: true });
        RadiusBottomLeft: =2
        RadiusBottomRight: =2
        RadiusTopLeft: =2
        RadiusTopRight: =2
        Size: =20
        Text: ="Error"
        Width: =218
        X: =1357
        Y: =943
        ZIndex: =9

    bltnShowCnfmn As button:
        BorderColor: |+
            =ColorFade(Self.Fill, -45%)
            
        Color: =RGBA(0, 0, 0, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Fill: =RGBA(241, 241, 241, 1)
        Height: =61
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(0, 51, 102, 1), -20%)
        OnSelect: |
            =Set(closeRequest, false );
            Set(blnShowMsgBarArea, true);
            UpdateContext({messageToShow:"This is a confirmation message created by component titled CompInfobar!"});
            UpdateContext({typeToShow:"Confirmation"});
            UpdateContext({blnShow: false });
            UpdateContext({blnShow: true });
        RadiusBottomLeft: =2
        RadiusBottomRight: =2
        RadiusTopLeft: =2
        RadiusTopRight: =2
        Size: =20
        Text: ="Confirmation"
        Width: =218
        X: =1628
        Y: =943
        ZIndex: =10

    CompInfoBar_1 As CompInfoBar:
        Fill: =RGBA(0, 0, 0, 0)
        Height: =80
        Message: =messageToShow
        Type: =typeToShow
        Visible: =blnShowMsgBarArea //Hide right after close button of the message bar clicked
        Width: =1727
        X: =192
        ZIndex: =11

    rtglMessage As label:
        BorderColor: =RGBA(0, 89, 178, 1)
        Color: =RGBA(118, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Semibold
        Height: =48
        Size: =20
        Text: ="MessageBar Demo(Max. 3 lines?)"
        Width: =470
        X: =810
        Y: =866
        ZIndex: =12

    Label4 As label:
        BorderColor: =RGBA(0, 89, 178, 1)
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(184, 0, 0, 1)
        Height: =95
        Size: =13
        Text: ="Text"
        Width: =1080
        X: =518
        Y: =498
        ZIndex: =13

