SC_CONFIG_MAIN As screen:
    Fill: =RGBA(219, 219, 219, 1)

    CompMenuVar_4 As CompMenuVar:
        Default: ="Config."
        items: =colLNBMenu
        Width: =100

    Label1_1 As label:
        BorderColor: =RGBA(0, 89, 178, 1)
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =48
        Size: =20
        Text: ="SC_CONFIG_MAIN" 
        Width: =461
        X: =471
        Y: =75
        ZIndex: =2

    CompColorPicker_1 As CompColorPicker:
        Height: =CompColorPicker_1.ReservedHeight
        OnReset: |
            =// ------------------------------------------------------------------------------------
            // -- UltimateColorPicker component
            // ------------------------------------------------------------------------------------
            // -- Author: Emmanuel GALLIS (on Twitter: @R3dKap)
            // -- Created: 08-sep-2019
            // -- First published: 29-nov-2019
            // ------------------------------------------------------------------------------------
            // -- History
            // -- 23-oct-2019 (v1.0): initial version
            // -- 01-dec-2019 (v1.1): added greyscale palette + fixed component auto-size + fixed
            //                        positionning of some controls + grouped controls inside
            //                        containers + prefixed hex output with "#"
            // ------------------------------------------------------------------------------------
            // No button selected
            Set(
                locSelectedButton,
                Blank()
            );
            // Set local default color to component's default color
            Set(
                locDefaultColor,
                Right(
                    CompColorPicker_1.DefaultColor,
                    Len(CompColorPicker_1.DefaultColor) - 1
                )
            );
            // Set current color red value based on default color
            Set(
                locPickedColorRed,
                Switch(
                    Right(
                        Left(
                            locDefaultColor,
                            2
                        ),
                        1
                    ),
                    "A",
                    10,
                    "B",
                    11,
                    "C",
                    12,
                    "D",
                    13,
                    "E",
                    14,
                    "F",
                    15,
                    Right(
                        Left(
                            locDefaultColor,
                            2
                        ),
                        1
                    )
                ) + Switch(
                    Left(
                        Left(
                            locDefaultColor,
                            2
                        ),
                        1
                    ),
                    "A",
                    10,
                    "B",
                    11,
                    "C",
                    12,
                    "D",
                    13,
                    "E",
                    14,
                    "F",
                    15,
                    Left(
                        Left(
                            locDefaultColor,
                            2
                        ),
                        1
                    )
                ) * 16
            );
            // Set current color green value based on default color
            Set(
                locPickedColorGreen,
                Switch(
                    Right(
                        Mid(
                            locDefaultColor,
                            3,
                            2
                        ),
                        1
                    ),
                    "A",
                    10,
                    "B",
                    11,
                    "C",
                    12,
                    "D",
                    13,
                    "E",
                    14,
                    "F",
                    15,
                    Right(
                        Mid(
                            locDefaultColor,
                            3,
                            2
                        ),
                        1
                    )
                ) + Switch(
                    Left(
                        Mid(
                            locDefaultColor,
                            3,
                            2
                        ),
                        1
                    ),
                    "A",
                    10,
                    "B",
                    11,
                    "C",
                    12,
                    "D",
                    13,
                    "E",
                    14,
                    "F",
                    15,
                    Left(
                        Mid(
                            locDefaultColor,
                            3,
                            2
                        ),
                        1
                    )
                ) * 16
            );
            // Set current color blue value based on default color
            Set(
                locPickedColorBlue,
                Switch(
                    Right(
                        Mid(
                            locDefaultColor,
                            5,
                            2
                        ),
                        1
                    ),
                    "A",
                    10,
                    "B",
                    11,
                    "C",
                    12,
                    "D",
                    13,
                    "E",
                    14,
                    "F",
                    15,
                    Right(
                        Mid(
                            locDefaultColor,
                            5,
                            2
                        ),
                        1
                    )
                ) + Switch(
                    Left(
                        Mid(
                            locDefaultColor,
                            5,
                            2
                        ),
                        1
                    ),
                    "A",
                    10,
                    "B",
                    11,
                    "C",
                    12,
                    "D",
                    13,
                    "E",
                    14,
                    "F",
                    15,
                    Left(
                        Mid(
                            locDefaultColor,
                            5,
                            2
                        ),
                        1
                    )
                ) * 16
            );
            // Set current color alpha value based on default color
            Set(
                locAlpha,
                If(
                    Mid(
                        locDefaultColor,
                        7,
                        2
                    ) <> "",
                    ((Switch(
                        Right(
                            Mid(
                                locDefaultColor,
                                7,
                                2
                            ),
                            1
                        ),
                        "A",
                        10,
                        "B",
                        11,
                        "C",
                        12,
                        "D",
                        13,
                        "E",
                        14,
                        "F",
                        15,
                        Right(
                            Mid(
                                locDefaultColor,
                                7,
                                2
                            ),
                            1
                        )
                    ) + Switch(
                        Left(
                            Mid(
                                locDefaultColor,
                                7,
                                2
                            ),
                            1
                        ),
                        "A",
                        10,
                        "B",
                        11,
                        "C",
                        12,
                        "D",
                        13,
                        "E",
                        14,
                        "F",
                        15,
                        Left(
                            Mid(
                                locDefaultColor,
                                7,
                                2
                            ),
                            1
                        )
                    ) * 16) / 255) * 100,
                    100
                )
            );
            // Initialize black to white palette (first color is Black)
            ClearCollect(
                locBlackWhiteColors,
                {Value: "#000000"}
            );
            // Build black to white palette (same number of shades than number of main colors)
            ForAll(
                CompColorPicker_1.MainColors,
                If(
                    Index > 1 && Index < CountRows(CompColorPicker_1.MainColors),// Skip first and last colors as they are respectively black and white
                    Collect(
                        locBlackWhiteColors,
                        {
                            Value: "#" & Switch(// Greyscale first digit for red value
                                RoundDown(
                                    Index * (255 / CountRows(CompColorPicker_1.MainColors)) / 16,
                                    0
                                ),
                                10,
                                "A",
                                11,
                                "B",
                                12,
                                "C",
                                13,
                                "D",
                                14,
                                "E",
                                15,
                                "F",
                                Text(
                                    RoundDown(
                                        Index * (255 / CountRows(CompColorPicker_1.MainColors)) / 16,
                                        0
                                    )
                                )
                            ) & Switch(// Greyscale second digit for red value
                                RoundDown(
                                    Mod(
                                        Index * (255 / CountRows(CompColorPicker_1.MainColors)),
                                        16
                                    ),
                                    0
                                ),
                                10,
                                "A",
                                11,
                                "B",
                                12,
                                "C",
                                13,
                                "D",
                                14,
                                "E",
                                15,
                                "F",
                                Text(
                                    RoundDown(
                                        Mod(
                                            Index * (255 / CountRows(CompColorPicker_1.MainColors)),
                                            16
                                        ),
                                        0
                                    )
                                )
                            ) & Switch(// Greyscale first digit for green value (same as red)
                                RoundDown(
                                    Index * (255 / CountRows(CompColorPicker_1.MainColors)) / 16,
                                    0
                                ),
                                10,
                                "A",
                                11,
                                "B",
                                12,
                                "C",
                                13,
                                "D",
                                14,
                                "E",
                                15,
                                "F",
                                Text(
                                    RoundDown(
                                        Index * (255 / CountRows(CompColorPicker_1.MainColors)) / 16,
                                        0
                                    )
                                )
                            ) & Switch(// Greyscale second digit for green value (same as red)
                                RoundDown(
                                    Mod(
                                        Index * (255 / CountRows(CompColorPicker_1.MainColors)),
                                        16
                                    ),
                                    0
                                ),
                                10,
                                "A",
                                11,
                                "B",
                                12,
                                "C",
                                13,
                                "D",
                                14,
                                "E",
                                15,
                                "F",
                                Text(
                                    RoundDown(
                                        Mod(
                                            Index * (255 / CountRows(CompColorPicker_1.MainColors)),
                                            16
                                        ),
                                        0
                                    )
                                )
                            ) & Switch(// Greyscale first digit for blue value (same as red and green)
                                RoundDown(
                                    Index * (255 / CountRows(CompColorPicker_1.MainColors)) / 16,
                                    0
                                ),
                                10,
                                "A",
                                11,
                                "B",
                                12,
                                "C",
                                13,
                                "D",
                                14,
                                "E",
                                15,
                                "F",
                                Text(
                                    RoundDown(
                                        Index * (255 / CountRows(CompColorPicker_1.MainColors)) / 16,
                                        0
                                    )
                                )
                            ) & Switch(// Greyscale second digit for blue value (same as red and green)
                                RoundDown(
                                    Mod(
                                        Index * (255 / CountRows(CompColorPicker_1.MainColors)),
                                        16
                                    ),
                                    0
                                ),
                                10,
                                "A",
                                11,
                                "B",
                                12,
                                "C",
                                13,
                                "D",
                                14,
                                "E",
                                15,
                                "F",
                                Text(
                                    RoundDown(
                                        Mod(
                                            Index * (255 / CountRows(CompColorPicker_1.MainColors)),
                                            16
                                        ),
                                        0
                                    )
                                )
                            )
                        }
                    )
                )
            );
            // Add last color to black and white palette: white
            Collect(
                locBlackWhiteColors,
                {Value: "#FFFFFF"}
            );
        Visible: =showColorPicker
        Width: =CompColorPicker_1.ReservedWidth
        X: =207
        ZIndex: =3

    Label2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(149, 149, 149, 1)
        BorderThickness: =2
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(232, 232, 232, 1)
        OnSelect: =Set(showColorPicker, true)
        Size: =13
        Text: ="Change Color Scheme"
        Width: =266
        X: =454
        Y: =330
        ZIndex: =4

