SC_CONFIG_MAIN As screen:
    Fill: =RGBA(219, 219, 219, 1)

    CompGNB_4 As CompGNBMenubar:
        Default: ="Config."
        Height: =Parent.Height
        items: =colLNBMenu
        Width: =181.26
        X: =0.00

    btnChangeColor As label:
        Align: =Align.Center
        BorderColor: =RGBA(149, 149, 149, 1)
        BorderThickness: =2
        Color: =RGBA(250, 250, 250, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Fill: =RGBA(0, 36, 71, 1)
        OnSelect: =Set(showColorPicker, true)
        PaddingRight: =7.25
        PaddingTop: =7.25
        Size: =18.85
        Text: ="Change Color Scheme"
        Width: =385.73
        X: =658.35
        Y: =330
        ZIndex: =3

    CompColorPicker_1 As CompColorPicker:
        Height: =CompColorPicker_1.ReservedHeight
        Visible: =showColorPicker
        Width: =1221.00
        X: =300.17
        ZIndex: =4

    Comp2ndMenu_4 As Comp2ndMenubar:
        Width: =1799.60
        X: =120.40000000000009
        Y: =35
        ZIndex: =5

    lblCurrentScrName_4 As label:
        BorderColor: =RGBA(0, 89, 178, 1)
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Height: =48
        PaddingRight: =7.25
        PaddingTop: =7.25
        Size: =21.76
        Text: =App.ActiveScreen.Name
        Width: =292.92
        X: =247.97
        Y: =573
        ZIndex: =6

